### ISSUE TITLE
Server crashing with little stack trace data

### ISSUE THREAD

**Issue by patlaff** [Mephi00/v-rising-wine-docker-image#19]
First of all, thank you for setting up this project. 

Starting after the hotfix was released on 6/15, my container is crashing on start up with the following stack trace:

```
vrising-server | ========== OUTPUTTING STACK TRACE ==================
vrising-server | 
vrising-server | RtlLookupFunctionEntry returned NULL function. Aborting stack walk.
vrising-server | 0x0000000180EE7265 (unityplayer) EntryPoint
vrising-server | 0x0000000180EE687C (unityplayer) EntryPoint
vrising-server | 0x000000018087D7C7 (unityplayer) EntryPoint
vrising-server | 0x00000001809ADBE7 (unityplayer) EntryPoint
vrising-server | 0x00007F3A037884F9 (gameassembly) il2cpp_class_enum_basetype
vrising-server | 0x00007F3A044AFD72 (gameassembly) il2cpp_class_enum_basetype
vrising-server | 0x00007F3A0202DC80 (gameassembly) il2cpp_class_enum_basetype
vrising-server | 0x00007F3A020306A8 (gameassembly) il2cpp_class_enum_basetype
vrising-server | 0x00007F3A0202DC80 (gameassembly) il2cpp_class_enum_basetype
vrising-server | 0x00007F3A01A11E42 (gameassembly) il2cpp_class_enum_basetype
vrising-server | 0x00007F3A020306A8 (gameassembly) il2cpp_class_enum_basetype
vrising-server | 0x00007F3A0202DC80 (gameassembly) il2cpp_class_enum_basetype
vrising-server | 0x00007F3A020306A8 (gameassembly) il2cpp_class_enum_basetype
vrising-server | 0x00007F3A0202DC80 (gameassembly) il2cpp_class_enum_basetype
vrising-server | 0x00007F3A020306A8 (gameassembly) il2cpp_class_enum_basetype
vrising-server | 0x00007F3A02D25EB2 (gameassembly) il2cpp_class_enum_basetype
vrising-server | 0x00007F3A00B7865C (gameassembly) il2cpp_class_enum_basetype
vrising-server | 0x00007F3A00B02EA9 (gameassembly) il2cpp_class_enum_basetype
vrising-server | 0x00000001808C6028 (unityplayer) EntryPoint
vrising-server | 0x00000001808C9092 (unityplayer) EntryPoint
vrising-server | 0x0000000180779756 (unityplayer) EntryPoint
vrising-server | 0x0000000180779770 (unityplayer) EntryPoint
vrising-server | 0x000000018077DA08 (unityplayer) EntryPoint
vrising-server | 0x000000018053DF8A (unityplayer) EntryPoint
vrising-server | 0x000000018053C44B (unityplayer) EntryPoint
vrising-server | 0x000000018054143B (unityplayer) EntryPoint
vrising-server | 0x000000018054254B (unityplayer) EntryPoint
vrising-server | 0x00000001400011F2 (vrisingserver) EntryPoint
vrising-server | <Missing stacktrace information>
vrising-server | 
vrising-server | ========== END OF STACKTRACE ===========
```

Base OS: Ubuntu 20.04.3 LTS

Docker-compose file:
```
version: "3.7"
services: 
  vrising: 
    image: mephi00/v-rising-wine:latest
    container_name: vrising-server
    volumes:
      - type: bind
        source: ./saves
        target: /saves
      - type: bind
        source: ./Settings
        target: /saves/Settings
    ports:
      - "9876-9877:9876-9877/udp"
    restart: unless-stopped
```

I can send more details if needed, but the issue is that the container log is providing very little information other than what I pasted from the stacktrace above.

I've tried changing the volume mounts a couple different ways, as I originally thought this was related to #6 , but no luck yet. Will continue to troubleshoot and respond with progress.
