### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by Johan-Claesson** [Mephi00/v-rising-wine-docker-image#2]
Hello! 
First of all, thanks for making this container! Really appreciate it! 

I have an issue with networking, see attached log file from container: 
![image](https://user-images.githubusercontent.com/81742448/170440522-a700caaa-c5ec-4939-a4bf-4b139b2695e9.png)

Does anyone knows what's going on? 

Here is my docker-compose file: 
```
version: "3"

services:
  vrising:
    container_name: v-rising
    image: mephi00/v-rising-wine
    volumes:
      - ${APPDATA}/v-rising:/saves
    ports:
      - 9876:9876/udp
      - 9877:9877/udp
    environment:
      - V_RISING_NAME=************
      - V_RISING_DESC=************
      - V_RISING_CLAN_SIZE=10
      - V_RISING_PASSW=************
      - V_RISING_SAVE_NAME=************
      - V_RISING_PUBLIC_LIST=true
      - V_RISING_SETTING_PRESET=Standard PvE Rules
      - PGID=${PGID}
      - PUID=${PUID}
    restart: unless-stopped
#    healthcheck:
#      test: wget -qO - ifconfig.me || exit 1
#      interval: 30s
#      retries: 10
#      start_period: 30s
#      timeout: 10s  
```

Also the .env file: 
```
TZ=Europe/Stockholm
UMASK=000
PUID=1000
PGID=1000
APPDATA=/games
COMPOSE_PROJECT_NAME=v-rising
```
